import { pool } from '../config/db';
import { diagnoseFailure } from './diagnosisEngine';
import { HttpError } from '../middleware/httpError';

export async function generateEscalationReport(incidentId: number): Promise<string> {
  const incidentResult = await pool.query(
    `SELECT i.*, ig.name AS integration_name
     FROM incidents i
     JOIN integrations ig ON i.integration_id = ig.id
     WHERE i.id = $1`,
    [incidentId]
  );
  const incident = incidentResult.rows[0];
  if (!incident) throw new HttpError(404, 'Incident not found');

  const evidenceResult = await pool.query(
    'SELECT * FROM evidence WHERE incident_id = $1 ORDER BY created_at DESC',
    [incidentId]
  );
  const evidence = evidenceResult.rows;

  const firstEvidence = evidence[0]?.content ? JSON.parse(evidence[0].content) : null;
  const status = firstEvidence?.status || 0;
  const diagnosis = diagnoseFailure(status);

  const evidenceText = evidence.map(e => {
    const parsed = JSON.parse(e.content);
    return `- **Request ID:** ${parsed.requestId}
- **Method:** ${parsed.method} ${parsed.endpoint}
- **Status:** ${parsed.status}
- **Latency:** ${parsed.latency}ms
- **Response:** ${parsed.responseBody || 'N/A'}`;
  }).join('\n\n');

  return `# Engineering Escalation Report

**Incident:** ${incident.title}  
**Severity:** ${incident.severity}  
**Status:** ${incident.status}  
**Integration:** ${incident.integration_name}  
**Created:** ${new Date(incident.created_at).toISOString()}

## Customer Impact
${incident.customer_impact}

## Reproduction Steps
1. Navigate to the integration configuration.
2. Trigger a request to ${incident.integration_name}.
3. Observe the failure.

## Expected Behavior
The integration should return a successful response.

## Actual Behavior
The integration returned an error (HTTP ${status}) or timed out.

## Evidence
${evidenceText}

## Probable Root Cause
${incident.probable_root_cause} (Confidence: ${Math.round(incident.confidence * 100)}%)

## Suggested Fix
${diagnosis.recommendedAction}

## Workaround
- Temporarily disable the integration or use a fallback.

---
*Generated by TraceDesk on ${new Date().toISOString()}*
`;
}
